### ISSUE TITLE
app/models/zip.rb

### ISSUE THREAD

**Issue by pacojp** [elecoma/elecoma#1]
1.9系だと以下でないとうまくファイルが読めませんでした

rawfile = open("jigyosyo.csv")
↓↓↓↓
rawfile = open("jigyosyo.csv",'r:Shift_JIS')

**Comment by hyoshida** [comment]
ご報告ありがとうございます。
郵便番号のインポートまわりは、ご指摘の部分を含めて現在改修しております。
いましばらくお待ちください。

**Comment by hyoshida** [comment]
＞pacojp様
お待たせしております。
46fafeae8272e01995d525681188d52a20821e9d と a26dfd9d531566036ecf07fad8b5eda83e8f17f5 にてご指摘の不具合を修正いたしました。

修正後、動作に問題がないことは確認済みですが、
pacojp様の環境でも動作することをご確認いただけないでしょうか。

よろしくお願いいたします。

**Comment by pacojp** [comment]
hyoshida様

お疲れ様です、pacojpです。

すみません、今コードを結構いじっちゃってるので（zip取り込めるように更新もしちゃっています）ちょっと今すぐ私の環境で確認するのは無理ですね

また時間ができましたら確認いたしますー
